version: 0.2
 
env:
  variables:
    AWS_DEFAULT_REGION: ap-east-1
    ECR_REPO_NAME: srujan-botique-repo
    IMAGE_TAG: latest
 
phases:
  install:
    runtime-versions:
      docker: 20
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install
 
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REPOSITORY_URI=${ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECR_REPO_NAME}
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${REPOSITORY_URI}
      - echo "Pre-build phase complete."
 
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t ${ECR_REPO_NAME}:${IMAGE_TAG} .
      - docker tag ${ECR_REPO_NAME}:${IMAGE_TAG} ${REPOSITORY_URI}:${IMAGE_TAG}
      - echo "Build phase complete."
 
  post_build:
    commands:
      - echo "Pushing image to ECR..."
      - docker push ${REPOSITORY_URI}:${IMAGE_TAG}
      - echo "Writing image definitions file..."
      - printf '[{"name":"myapp-container","imageUri":"%s"}]' ${REPOSITORY_URI}:${IMAGE_TAG} > imagedefinitions.json
      - echo "Post-build phase complete."
 
artifacts:
  files:
    - imagedefinitions.json